### ISSUE TITLE
google colaboratoryがいい感じ

### ISSUE THREAD

**Issue by suzucan2020** [CodeSeterpie/CodeSeterpie#15]
機械学習などをやろうとすると処理時間がかかる。
GPUなどを用いれば数時間の処理を数分で処理することができるが費用がかかる。
クラウドを使えば使用した分だけの料金を払えばいいので、取っ掛かりにはよさそう。
AWSなどを調べたが、今のところgoogle colaboratoryがだいぶいい感じに思える。
70万くらいするGPUやTensorFlow向けに最適化されたチップであるTPUが無料で使えるのがすごい。

**Comment by uragami-lab** [comment]
クラウドサーバー上に容易に実行環境を構築できることも、実行環境のベースにDockerを選んだ理由の一つです。  
機械学習などの分析処理と、ウェブサイトのクローリングとスクレイピングを使った情報収集処理を同じクラウドサーバー上に置いて、情報収集と分析を継続的に行い、意味のあるものを生み出し続ける仕組みも面白そうだなと考えています。

**Comment by uragami-lab** [comment]
google colaboratory はGPUやTPUが付いたクラウドサーバーを貸してもらえるのでは無く、クラウドで動くJupyter notebookの環境なんですね。  
そうすると今自分たちがGitHubで作っているJupyter notebookをどうやって連携して、google colaboratory で動かせるのかが気になるところです。

**Comment by uragami-lab** [comment]
[PredictFutureSales](https://github.com/CodeSeterpie/CodeSeterpie/tree/develop/Kaggle/PredictFutureSales)でgoogle colaboratoryを導入できたのでクローズにします。
