### ISSUE TITLE
分析結果を可視化する必要がある。

### ISSUE THREAD

**Issue by uragami-lab** [CodeSeterpie/CodeSeterpie#17]
分析結果がどの程度真の値と異なっているのかは、現状ではKaggleへ提出した結果のスコア、もしくは自前で計算したRMSEでしかわからない。  
どの程度ずれているのかわかりやすくするには可視化すればいいと思う。

**Comment by suzucan2020** [comment]
今まではデータを選別するための可視化であったが、スコアを上げるためには決定木の可視化が必須な気がします。

どれがいいのか全く分からないがメモがてら検索したものをいかに上げておきます。

LIME
https://qiita.com/_qsng/items/7c922a983b21653acbae

LightGBM の学習が進む様子は、学習させるときにオプションとして verbose_eval などを指定することでコンソールから確認できる。
https://blog.amedama.jp/entry/lightgbm-learning-curve-dynamic-plot

dtreeviz
https://www.st-hakky-blog.com/entry/2018/09/30/172910

graphviz
http://www.matools.com/lang-jp/blog/190134326

**Comment by uragami-lab** [comment]
LIMEがいいかなと思います。理由としては下の通り。
* 今使っているLightGBMライブラリに対応している(dtreevizは[このコメント](https://github.com/parrt/dtreeviz/issues/15)を見る限り対応してなさそう)
* [LIMEのGithubページ](https://github.com/marcotcr/lime)のStarの数が7.1K、[dtreevizのGithubページ](https://github.com/parrt/dtreeviz)のStarの数が1Kなので、LIMEの方が人気がある。
* sklearnの標準は見た目がわかりづらい(野暮ったい)

**Comment by uragami-lab** [comment]
結果をシンプルにmatplotlibを使って可視化している下のサイトも参考になる。
http://www2.kaiyodai.ac.jp/~takenawa/learning/Keras_regression.html

**Comment by uragami-lab** [comment]
[2020/2/29の活動](https://github.com/CodeSeterpie/CodeSeterpie/wiki/%E6%B4%BB%E5%8B%95%E8%A8%98%E9%8C%B2-20200229)で結果の可視化ができたため、クローズとします。
