### ISSUE TITLE
どのカテゴリ変数をモデルに与えたらいいのか判断がつかない。

### ISSUE THREAD

**Issue by uragami-lab** [CodeSeterpie/CodeSeterpie#19]
カテゴリ変数をラベルエンコーディング等で変換してモデルに渡しても、一体どの変数をモデルに渡せばいいのか判断がつかない。

**Comment by suzucan2020** [comment]
カテゴリを全部渡した結果が前回のスコアを上回ったため、
カテゴリ変数を絞る必要は今のところ必要ないことがわかった。
よってこのissueをクローズする。
