### ISSUE TITLE
分析にかかる時間を短縮しておきたい。

### ISSUE THREAD

**Issue by uragami-lab** [CodeSeterpie/CodeSeterpie#23]
分析に時間がかかってしまう端末を使っている場合や、モデルチューニングの時など分析を複数回実行しなければならない場合に対応できるよう、分析にかかる時間を短縮できるようにしておきたい。

案としてはクラウドサーバーに実行環境を構築して、リモートでつないで実行することが考えられる。また、#15 で教えてもらったgoogle colaboratoryも有力候補。

**Comment by uragami-lab** [comment]
GBDT(勾配ブースティング木)モデルを使うために今はxgboostライブラリをインポートしていが、このライブラリよりも高速な[LightGBM](https://www.codexa.net/lightgbm-beginner/)を使うのも手だと思う。  
ただ、今のDocker環境にLightGBMを追加する方法が不明。

**Comment by suzucan2020** [comment]
LightGBMライブラリを使用したところ、処理時間を短縮できたため、現状はこの方法で進めていく。
よってこのissueをクローズする。
