### ISSUE TITLE
jupyterでのコーディング作業を効率化したい

### ISSUE THREAD

**Issue by suzucan2020** [CodeSeterpie/CodeSeterpie#27]
jupyterにvisualstudioやvimの拡張機能にある、自動補完や、Lint(リント)機能を追加し
コーディングの効率化やミスを減らしたい。

以下を使うのがよさげだっため現在取り組み中。
https://github.com/krassowski/jupyterlab-lsp

jupyter　lsp　で検索しとりあえず以下をDockerfileに追加してお試し中。
とりあえず自動補完やリント機能が動作している模様。

RUN pip install --upgrade pip
RUN pip install jupyterlab
RUN jupyter serverextension enable --py jupyterlab
RUN jupyter labextension install @krassowski/jupyterlab-lsp
RUN pip install 'python-language-server[all]'
RUN pip install --pre jupyter-lsp

**Comment by uragami-lab** [comment]
既存である自動補完は動作が遅く使いづらいので、この機能追加で使いやすくなって欲しいです!   
リント機能は使ったことがないので楽しみです。

**Comment by suzucan2020** [comment]
jupyterlab-lspだがうまく動作させることができなかった。
pd.←この時はうまく動作してくれるが
df.←この時はうまく動作しなかった

またリント機能もうまく動作していない感じであった。
そのため、補完はデフォルトのものを使い、リント機能や自動整形のみ拡張するのがよいかと思う。

現在は以下をDockerfileに追加して使用中

#リント機能を追加
RUN pip install flake8
RUN jupyter labextension install jupyterlab-flake8

#コードの自動整形を追加
RUN pip install black
RUN pip install yapf
RUN pip install autopep8
RUN pip install jupyterlab_code_formatter
RUN jupyter labextension install @ryantam626/jupyterlab_code_formatter
RUN jupyter serverextension enable --py jupyterlab_code_formatter

機能を有効にするには、以下を参考に

https://github.com/mlshapiro/jupyterlab-flake8

https://qrunch.net/@lay1884/entries/l35M2e9jonlL7hID

setting→advanced setting editorの
Keyboard Shortcuts
Jupyterlab Code Formatter
Jupyterlab-Flake8
を編集する必要がある。

**Comment by uragami-lab** [comment]
現状、うまく動作していないのは残念ですが、pushしてもらったコードを参考にして、「JupyterLabの設定ファイルがdocker container再作成時に初期化されてしまう #7」の不具合を解消することができました。
