### ISSUE TITLE
Jupyter notebookのコード部分のみの差分を見れるようにしたい

### ISSUE THREAD

**Issue by uragami-lab** [CodeSeterpie/CodeSeterpie#48]
Jupyter notebookファイル(.ipynbファイル)をgitで差分をみると、出力内容やセルの設定も含まれてしまうため、コードの変更点が見づらいので、コード部分のみの差分に絞れると作業効率が上がると思う。

候補 : [nbdime](https://nbdime.readthedocs.io/en/latest/index.html#)

**Comment by suzucan2020** [comment]
ipynbファイルをpyファイルに変換する方法もあるみたいです。

以下コマンド

```
jupyter nbconvert --to script *.ipynb
```

参考URL
https://qiita.com/abts/items/25bb611b6d83e646abdd

**Comment by uragami-lab** [comment]
手動でpyファイル変換は大変なので、JupyterLab の拡張機能の[Jupytext](https://github.com/mwouts/jupytext)を入れてみようと思います。Jupytextは自動でipynbファイルと同期するpyを作ってくれるので、githubにプッシュするときに、ipynbファイルと、pyファイルの両方をプッシュしてもらえば良い感じです。  
また、pyを自分の好みのエディタで編集して、JupyterLabから開くとipynbに自動で反映してくれるというメリットもあります。

日本語の参考HP: https://qiita.com/cfiken/items/8455383f32ee19dfbba3

**Comment by suzucan2020** [comment]
jupyterlabの拡張機能はいろいろ使えこなせるようになると便利そうですね。

あとは、面白そうなのはgithub　action（CI/CD）を使ってみる、ですかね。
pushなどトリガーに裏でシェルなどが走って、コマンド実行を自動化できます。

他の人が作成した自動化のコードも公開されてるので、使いこなせるようになるとかなり強力そうです。
例えば、予測したcsvをkaggleに自動で提出する、毎日12時に株価を取得させるなど。


以下を使うと、pushをトリガーにipynb→pyにしてくれるみたいです。
https://github.com/marketplace/actions/autopy-lot

**Comment by uragami-lab** [comment]
github action うまく使っていきたいですね。いろいろ面白いことができそうです。
CodeSeterpieは無料アカウントなので、actionは2,000分/月の縛りがあるので大事に使いましょう。
