### ISSUE TITLE
ニューラルネットワークモデルを使って分析をしたい

### ISSUE THREAD

**Issue by uragami-lab** [CodeSeterpie/CodeSeterpie#5]
ニューラルネットワークモデルを使った分析の実装はできていないため、このモデルを使った実装をしてみたい。  
ライブラリは使いやすいというKerasがいいと思う。

**Comment by suzucan2020** [comment]
keras気になってます。

**Comment by uragami-lab** [comment]
今使っているDocker imageにはkerasが含まれるため、すぐに実装できる。  
kerasを呼び出す場合は`from tensorflow import keras`でインポートする。

**Comment by uragami-lab** [comment]
2020/2/15の活動で実際に実装してみたので、クローズします。

* 実装したnotebook  
[/Kaggle/HousePrices/notebook/main/20200215/note_keras.ipynb](https://github.com/CodeSeterpie/CodeSeterpie/blob/develop/Kaggle/HousePrices/notebook/main/20200215/note_keras.ipynb)
