### ISSUE TITLE
処理がかかる部分はプログレスバーを表示したい

### ISSUE THREAD

**Issue by suzucan2020** [CodeSeterpie/CodeSeterpie#58]
参考URL
- https://orizuru.io/blog/python/python_progressbar/
- https://qiita.com/halhorn/items/e8aaf5b63f493f038a53
- http://esu-ko.hatenablog.com/entry/2016/02/28/Python%E3%81%A7%E3%83%97%E3%83%AD%E3%82%B0%E3%83%AC%E3%82%B9%E3%83%90%E3%83%BC%E3%82%92%E5%87%BA%E3%81%97%E3%81%9F%E3%81%84%28tqdm%E3%82%92%E4%BD%BF%E3%81%86%29
- https://stackoverflow.com/questions/42212810/tqdm-in-jupyter-notebook-prints-new-progress-bars-repeatedly

**Comment by uragami-lab** [comment]
確かに時間のかかる処理にプログレスバーがあるといいですね！  
ざっと参考URLをみましたが、ライブラリをインストールして、コードにインポートするだけのようですね。  

下のDockerfileにインストールの記載を追加して試してみて、良い感じのやつがあってプルリクエスト出してくれれば、本体にマージしますよ!
https://github.com/CodeSeterpie/CodeSeterpie/blob/develop/Kaggle/HousePrices/docker/jupyter/Dockerfile

インストールはconda installで統一しているので、これでインストールするようにしてください。condaになければpipでインストールしてください。
