### ISSUE TITLE
JupyterLabの設定ファイルがdocker container再作成時に初期化されてしまう

### ISSUE THREAD

**Issue by uragami-lab** [CodeSeterpie/CodeSeterpie#7]
JupyterLabの設定(テーマやキーバインド等)はcontainer内に設定ファイルが格納されているため、docker containerが再作成されると初期化されてしまう。  
いちいち設定し直すのも面倒なので、初期化されないようにしたい。

**Comment by suzucan2020** [comment]
スマートな解決方法ではないが、一時的な解決策としては、docker cp で設定ファイルを
ホストに退避してコンテナ作成後に再度 docker cp で上書きする感じですかね。
